
- name: Maak gebruikers en genereer SSH-sleutels
  hosts:
    - pm01
    - pm02
    - pm03
  vars:
    users:
      - username: numbero_uno
        pubkey_file: numbero_uno.pub
      - username: numbero_dos
        pubkey_file: numbero_dos.pub

  tasks:
    - name: Maak gebruikers aan
      user:
        name: "{{ item.username }}"
        createhome: yes
      with_items: "{{ users }}"

    - name: Create .ssh directory
      file:
        path: "/home/{{ item.username }}/.ssh"
        state: directory
      with_items: "{{ users }}"

    - name: Genereer SSH-sleutels
      openssh_keypair:
        path: "/home/{{ item.username }}/.ssh/id_rsa"
        state: present
      with_items: "{{ users }}"

    - name: Voeg publieke sleutels toe aan authorized_keys
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', item.pubkey_file) }}"
      with_items: "{{ users }}"


###
### EspoCRM installatie
###


- name: Automate EspoCRM Deployment
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Create VMs on pm01
      proxmox_kvm:
        node: pm01
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net0: virtio,bridge=vmbr0
        virtio0: local:50
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 100, hostname: "espocrm-vm1" }

    - name: Create VMs on pm02
      proxmox_kvm:
        node: pm02
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net0: virtio,bridge=vmbr0
        virtio0: local:50
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 101, hostname: "espocrm-vm2" }

    - name: Create VMs on pm03
      proxmox_kvm:
        node: pm03
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net0: virtio,bridge=vmbr0
        virtio0: local:50
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 102, hostname: "espocrm-vm3" }


###
### de nodes nu toevoegen aan het host bestand en een snapshot maken
###

    - name: Add espocrm_vms to group
      add_host:
        name: "{{ item.hostname }}"
        groups: espocrm_vms
      loop:
        - { node: pm01, vmid: 100, hostname: "espocrm-vm1" }
        - { node: pm02, vmid: 101, hostname: "espocrm-vm2" }
        - { node: pm03, vmid: 102, hostname: "espocrm-vm3" }



    - name: Take snapshots
      hosts: espocrm_vms
      become: yes
      community.general.proxmox_kvm_snapshot:
        node: "{{ item.node }}"
        vmid: "{{ item.vmid }}"
        name: "daily_snapshot"
        state: present
      loop:
        - { node: pm01, vmid: 100 }
        - { node: pm02, vmid: 101 }
        - { node: pm03, vmid: 102 }

###
### installeren van espocrm op de vms
###

    - name: Install espocrm on the VMs
      hosts: espocrm_vms
      become: yes
      shell: |
        wget https://github.com/espocrm/espocrm-installer/releases/latest/download/install.sh
        sudo bash install.sh -y --ssl --letsencrypt --domain=cloud-espocrm.com --clean
      args:
        chdir: /root #ALLEEN LATEN DRAAIEN ALS ESPOCRM NOG NIET GEINSTALEERD IS!!!


