###
### Het aanmaken van de 2 gebrukers +ssh sleutels
###

- name: Maak gebruikers en genereer SSH-sleutels
  hosts:
    - pm01
    - pm02
    - pm03
  become: yes
  vars:
    users:
      - username: numbero_uno
        pubkey_file: id_rsa.pub
      - username: numbero_dos
        pubkey_file: id_rsa.pub

  tasks:
    - name: Maak gebruikers aan
      user:
        name: "{{ item.username }}"
        createhome: yes
      with_items: "{{ users }}"

    - name: Zet de rechten van .ssh directory
      file:
        path: "/home/{{ item.username }}/.ssh"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: "0700"
      with_items: "{{ users }}"

    - name: Genereer SSH-sleutels
      openssh_keypair:
        path: "/home/{{ item.username }}/.ssh/id_rsa"
        state: present
      with_items: "{{ users }}"

    - name: Lees de inhoud van id_rsa.pub
      ansible.builtin.shell: cat /home/{{ item.username }}/.ssh/id_rsa.pub
      loop: "{{ users }}"
      register: public_key_data

    - name: Zet de publieke sleutels in een lijst
      set_fact:
        public_keys: "{{ public_keys | default([]) + [item.stdout] }}"
      loop: "{{ public_key_data.results }}"
      vars:
        public_keys: [ ]

    - name: Sla de publieke sleutels op in een bestand
      copy:
        content: "{{ public_keys | join('\n') }}"
        dest: "/home/{{ inventory_hostname }}_public_keys"
      delegate_to: localhost

    - name: Lees de publieke sleutels uit het bestand
      ansible.builtin.shell: cat /home/{{ item }}_public_keys
      register: all_public_key_data
      loop: "{{ groups['all'] }}"
      delegate_to: localhost

    - name: Zet alle publieke sleutels in een lijst
      set_fact:
        all_public_keys: "{{ all_public_keys | default([]) + [item.stdout] }}"
      loop: "{{ all_public_key_data.results }}"
      vars:
        all_public_keys: [ ]

    - name: Toon de publieke sleutels
      debug:
        var: all_public_keys

    - name: Voeg publieke sleutels toe aan authorized_keys
      ansible.builtin.lineinfile:
        path: "/home/{{ item.0.username }}/.ssh/authorized_keys"
        line: "{{ item.1 }}"
        create: yes
      loop: "{{ users | product(all_public_keys) | list }}"


###
### EspoCRM installatie
###


- name: Automate EspoCRM Deployment
  hosts: localhost
  gather_facts: no
  become: yes

  tasks:
    - name: Create VMs on pm01
      proxmox_kvm:
        node: pm01
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net0: virtio,bridge=vmbr0
        virtio0: local:50
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 100, hostname: "espocrm-vm1" }

    - name: Create VMs on pm02
      proxmox_kvm:
        node: pm02
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net0: virtio,bridge=vmbr0
        virtio0: local:50
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 101, hostname: "espocrm-vm2" }

    - name: Create VMs on pm03
      proxmox_kvm:
        node: pm03
        vmid: "{{ item.vmid }}"
        hostname: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net0: virtio,bridge=vmbr0
        virtio0: local:50
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 102, hostname: "espocrm-vm3" }


###
### de nodes nu toevoegen aan het host bestand en een snapshot maken
###

    - name: Add espocrm_vms to group
      add_host:
        name: "{{ item.hostname }}"
        groups: espocrm_vms
      loop:
        - { node: pm01, vmid: 100, hostname: "espocrm-vm1" }
        - { node: pm02, vmid: 101, hostname: "espocrm-vm2" }
        - { node: pm03, vmid: 102, hostname: "espocrm-vm3" }



    - name: Take snapshots
      hosts: espocrm_vms
      become: yes
      community.general.proxmox_kvm_snapshot:
        node: "{{ item.node }}"
        vmid: "{{ item.vmid }}"
        name: "daily_snapshot"
        state: present
      loop:
        - { node: pm01, vmid: 100 }
        - { node: pm02, vmid: 101 }
        - { node: pm03, vmid: 102 }

###
### installeren van espocrm op de vms
###

    - name: Install espocrm on the VMs
      hosts: espocrm_vms
      become: yes
      shell: |
        wget https://github.com/espocrm/espocrm-installer/releases/latest/download/install.sh
        sudo bash install.sh -y --ssl --letsencrypt --domain=cloud-espocrm.com --clean
      args:
        chdir: /root #ALLEEN LATEN DRAAIEN ALS ESPOCRM NOG NIET GEINSTALEERD IS!!!


