###
### EspoCRM installatie
###


- name: Automate EspoCRM Deployment
  hosts: localhost
  gather_facts: no
  become: yes

  vars:
    pm01: 172.16.39.70
    pm02: 172.16.39.71
    pm03: 172.16.39.72

  vars_prompt:
    - name: "api_password"
      prompt: "Enter the Proxmox API password"
      private: yes

  tasks:
    - name: Updaten van packets...
      apt:
        update_cache: yes

    - name: Install Python 3 and pip
      become: yes
      become_user: root
      command: apt install -y python3 python3-pip

    - name: Install proxmoxer
      ansible.builtin.pip:
        name: proxmoxer
        executable: pip3

    - name: Create VMs on pm01
      proxmox_kvm:
        api_user: 422422@pve
        api_password: "{{ api_password }}"
        api_host: "{{ pm01 }}"
        node: "{{ pm01 }}"
        vmid: "{{ item.vmid }}"
        name: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net: '{"net0":"virtio,bridge=vmbr0"}'
        virtio: '{"virtio0":"local:50"}'
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 100, hostname: "espocrm-vm1" }

    - name: Create VMs on pm02
      proxmox_kvm:
        api_user: 422422@pve
        api_password: "{{ api_password }}"
        api_host: "{{ pm02 }}"
        node: "{{ pm02 }}"
        vmid: "{{ item.vmid }}"
        name: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net: '{"net0":"virtio,bridge=vmbr0"}'
        virtio: '{"virtio0":"local:50"}'
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 101, hostname: "espocrm-vm2" }

    - name: Create VMs on pm03
      proxmox_kvm:
        api_user: 422422@pve
        api_password: "{{ api_password }}"
        api_host: "{{ pm03 }}"
        node: "{{ pm03 }}"
        vmid: "{{ item.vmid }}"
        name: "{{ item.hostname }}"
        memory: 2
        cores: 2
        net: '{"net0":"virtio,bridge=vmbr0"}'
        virtio: '{"virtio0":"local:50"}'
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
      loop:
        - { vmid: 102, hostname: "espocrm-vm3" }



###
### de nodes nu toevoegen aan het host bestand en een snapshot maken
###

    - name: Add espocrm_vms to group
      add_host:
        name: "{{ item.hostname }}"
        groups: espocrm_vms
      loop:
        - { node: pm01, vmid: 100, hostname: "espocrm-vm1" }
        - { node: pm02, vmid: 101, hostname: "espocrm-vm2" }
        - { node: pm03, vmid: 102, hostname: "espocrm-vm3" }

- name: Create snapshot script on Proxmox hosts
  hosts: pm01,pm02,pm03
  become: yes
  tasks:
    - name: Create snapshot script
      copy:
        dest: "/root/snapshot_vms.sh"
        content: |
          #!/bin/bash
          for vmid in 100 101 102; do
            pct snapshot $vmid daily_snapshot
          done
        mode: 0755

    - name: Create cron job for snapshotting VMs twice a day
      cron:
        name: "snapshot job"
        minute: "0"
        hour: "*/12"
        job: "/root/snapshot_vms.sh"


- name: EspoCRM VMs instellen
  hosts: espocrm_vms
  become: yes

  tasks:
###
### installeren van espocrm op de vms
###

    - name: Check if EspoCRM is installed
      stat:
        path: /path/to/espocrm
      register: espocrm_dir

    - name: Install espocrm on the VMs
      shell: |
        wget https://github.com/espocrm/espocrm-installer/releases/latest/download/install.sh
        sudo bash install.sh -y --ssl --letsencrypt --domain=cloud-espocrm.com --clean
      args:
        chdir: /root
      register: espocrm_install
      when: not espocrm_dir.stat.exists

    - debug:
        var: espocrm_install.stdout_lines




