###
### EspoCRM installatie
###

- name: Voeg CIFS gedeelde opslag toe aan Proxmox
  hosts:
    - pm01
    - pm02
    - pm03
  vars_prompt:
    - name: cifs_password
      prompt: "Voer het wachtwoord in voor CIFS gedeelde opslag"
      private: yes
  tasks:

    - name: Controleer of CIFS gedeelde opslag al bestaat
      shell: cat /etc/pve/storage.cfg | grep shared_storage
      register: shared_storage_check
      ignore_errors: yes

    - name: Voer het pvesm commando uit om CIFS gedeelde opslag toe te voegen
      command: pvesm add cifs shared_storage --server 172.16.0.100 --share 422422 --username student422422 --password "{{ cifs_password }}"
      when: shared_storage_check.stdout == ""

    - name: Add entry to /etc/fstab for shared storage
      lineinfile:
        path: /etc/fstab
        line: "//172.16.0.100/shared_storage /shared_storage cifs username=student422422,password={{ cifs_password }},rw 0 0"
        state: present
      when: "not (lookup('file', '/etc/fstab') | regex_search('172.16.0.100/shared_storage'))"


- name: Voeg Proxmox template toe aan Proxmox01
  hosts:
    - pm01
  tasks:
    - name: Create a Proxmox template (dit kan even duren....)
      shell: |
        wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
        virt-customize -a focal-server-cloudimg-amd64.img --install qemu-guest-agent --root-password password:422422
        qm create 8999 --name "ubuntu-2004-cloudinit-template1" --memory 2048 --cores 2 --net0 virtio,bridge=vmbr0
        qm importdisk 8999 focal-server-cloudimg-amd64.img local-lvm
        qm set 8999 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-8999-disk-0
        qm set 8999 --boot c --bootdisk scsi0
        qm set 8999 --ide2 local-lvm:cloudinit
        qm set 8999 --serial0 socket --vga serial0
        qm set 8999 --agent enabled=1
        qm resize 9001 scsi0 6G
        qm template 8999


- name: Voeg Proxmox template toe aan Proxmox02
  hosts:
    - pm02
  tasks:
    - name: Create a Proxmox template (dit kan even duren....)
      shell: |
        wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
        virt-customize -a focal-server-cloudimg-amd64.img --install qemu-guest-agent --root-password password:422422
        qm create 9000 --name "ubuntu-2004-cloudinit-template2" --memory 2048 --cores 2 --net0 virtio,bridge=vmbr0
        qm importdisk 9000 focal-server-cloudimg-amd64.img local-lvm
        qm set 9000 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-9000-disk-0
        qm set 9000 --boot c --bootdisk scsi0
        qm set 9000 --ide2 local-lvm:cloudinit
        qm set 9000 --serial0 socket --vga serial0
        qm set 9000 --agent enabled=1
        qm resize 9001 scsi0 6G
        qm template 9000

- name: Voeg Proxmox template toe aan Proxmox03
  hosts:
    - pm03
  tasks:
    - name: Create a Proxmox template (dit kan even duren....)
      shell: |
        wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
        virt-customize -a focal-server-cloudimg-amd64.img --install qemu-guest-agent --root-password password:422422
        qm create 9001 --name "ubuntu-2004-cloudinit-template3" --memory 2048 --cores 2 --net0 virtio,bridge=vmbr0
        qm importdisk 9001 focal-server-cloudimg-amd64.img local-lvm
        qm set 9001 --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-9001-disk-0
        qm set 9001 --boot c --bootdisk scsi0
        qm set 9001 --ide2 local-lvm:cloudinit
        qm set 9001 --serial0 socket --vga serial0
        qm set 9001 --agent enabled=1
        qm resize 9001 scsi0 6G
        qm template 9001




- name: Automate EspoCRM Deployment
  hosts: localhost
  gather_facts: no
  become: yes

  ###
  ### vars gebruiken zodat dit script ook scalable is
  ###

  vars: #verander dit als je andere IPs hebt en andere nodenamen
    pm01: 172.16.39.70
    pm02: 172.16.39.71
    pm03: 172.16.39.72
    node1: geenboom2
    node2: geenboom3
    node3: geenboom4


  ###
  ### Wachtwoorden prompten zodat hij niet hardcoded in het script staat
  ###

  vars_prompt:
    - name: "api_password"
      prompt: "Enter the Proxmox API password"
      private: yes

  tasks:
    - name: Updaten van packets...
      apt:
        update_cache: yes

    - name: Install Python 3 and pip
      become: yes
      become_user: root
      command: apt install -y python3 python3-pip

    - name: Installeer proxmoxer en requests met pip
      ansible.builtin.pip:
        name:
          - proxmoxer
          - requests
        executable: pip3

    - name: installeren van community.general collectie
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.general

    ##
    ##EspoCRM VMs aanmaken met disk 50G/2 proc/2GB mem ne statische IP toekennen
    ##
    ###
    ### PM01
    ###
    - name: Create VMs on pm01
      proxmox_kvm:
        api_user: root@pam
        api_password: "{{ api_password }}"
        api_host: "{{ pm01 }}"
        node: "{{ node1 }}"
        name: "{{ item.hostname }}"
        clone: "{{ item.template }}"
        newid: "{{ item.vmid }}"
        memory: 2048
        cores: 2
        net: '{"net0":"virtio,bridge=vmbr0"}'
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
        ipconfig: '{"ipconfig0":"ip={{ item.ip }}/16,gw=172.16.0.1"}'
        agent: '1'
        timeout: 300
      loop:
        - { template: "ubuntu-2004-cloudinit-template1", vmid: 100, hostname: "espocrmvm1", ip: "172.16.39.100" }

    ##
    ## PM02
    ##

    - name: Create VMs on pm02
      proxmox_kvm:
        api_user: root@pam
        api_password: "{{ api_password }}"
        api_host: "{{ pm02 }}"
        node: "{{ node2 }}"
        name: "{{ item.hostname }}"
        clone: "{{ item.template }}"
        newid: "{{ item.vmid }}"
        memory: 2048
        cores: 2
        net: '{"net0":"virtio,bridge=vmbr0"}'
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
        ipconfig: '{"ipconfig0":"ip={{ item.ip }}/16,gw=172.16.0.1"}'
        agent: '1'
        timeout: 300
      loop:
        - { template: "ubuntu-2004-cloudinit-template2", vmid: 101, hostname: "espocrmvm2", ip: "172.16.39.101" }

    ###
    ### PM03
    ###

    - name: Create VMs on pm03
      proxmox_kvm:
        api_user: root@pam
        api_password: "{{ api_password }}"
        api_host: "{{ pm03 }}"
        node: "{{ node3 }}"
        name: "{{ item.hostname }}"
        clone: "{{ item.template }}"
        newid: "{{ item.vmid }}"
        memory: 2048
        cores: 2
        net: '{"net0":"virtio,bridge=vmbr0"}'
        onboot: yes
        ostype: l26 # Ubuntu 20.04 LTS
        ipconfig: '{"net0":"ip={{ item.ip }}/16,gw=172.16.0.1"}'
        agent: '1'
        timeout: 300
      loop:
        - { template: "ubuntu-2004-cloudinit-template3", vmid: 102, hostname: "espocrmvm3", ip: "172.16.39.102" }


- name: Voeg shared_storage toe aan Proxmox01
  hosts:
    - pm01
  tasks:
    - name: toevoegen....
      shell: |  
        qm set 100 --virtio0 shared_storage:50,format=qcow2
        qm set 100 --ipconfig0 ip=172.16.39.100/16,gw=172.16.0.1
        qm set 100 --sshkey /root/.ssh/id_rsa.pub

- name: Voeg shared_storage toe aan Proxmox02
  hosts:
    - pm02
  tasks:
    - name: toevoegen....
      shell: |
        qm set 101 --virtio0 shared_storage:50,format=qcow2
        qm set 101 --ipconfig0 ip=172.16.39.101/16,gw=172.16.0.1
        qm set 101 --sshkey /root/.ssh/id_rsa.pub

- name: Voeg shared_storage toe aan Proxmox03
  hosts:
    - pm03
  tasks:
    - name: toevoegen....
      shell: |
        qm set 102 --virtio0 shared_storage:50,format=qcow2
        qm set 102 --ipconfig0 ip=172.16.39.102/16,gw=172.16.0.1
        qm set 102 --sshkey /root/.ssh/id_rsa.pub
  


    ###
    ### espocrm_vms groep aanmaken
    ###
- name: Automate EspoCRM Deployment
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: espocrm_vms group maken
      add_host:
        name: "{{ item.hostname }}"
        groups: espocrm_vms
        node: "{{ item.node }}"
        vmid: "{{ item.vmid }}"
        ip: "{{ item.ip }}"
      loop:
        - { node: "pm01", vmid: 100, hostname: "espocrmvm1", ip: "172.16.39.101" }
        - { node: "pm02", vmid: 101, hostname: "espocrmvm2", ip: "172.16.39.102" }
        - { node: "pm03", vmid: 102, hostname: "espocrmvm3", ip: "172.16.39.103" }

    - name: VMs tevoegen aan hosts file
      lineinfile:
        path: /home/geenboom1/ansible_wordpress_project/hosts
        line: "\n[{{ item.hostname }}]\n{{ item.ip }}"
        state: present
      become: yes
      loop:
        - { hostname: "espocrmvm1", ip: "172.16.39.101" }
        - { hostname: "espocrmvm2", ip: "172.16.39.102" }
        - { hostname: "espocrmvm3", ip: "172.16.39.103" }