- name: subscriptie uitetten
  hosts:  # Hosts waarop je deze taak wilt uitvoeren
    - pm01
    - pm02
    - pm03
  become: true  # root
  tasks:
    - name: Voeg Proxmox no-subscription repository toe
      blockinfile:
        path: /etc/apt/sources.list
        insertbefore: '## Main'  # toevoegen
        block: |
          # Proxmox VE pve-no-subscription repository provided by proxmox.com,
          # NOT recommended for production use
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
          #normalle pakketten van debian
          deb http://deb.debian.org/debian buster main contrib non-free
          deb-src http://deb.debian.org/debian buster main contrib non-free
    - name: pve-enterprise repository weghalen
      lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb'
        line: '# deb'
        state: present

###
### docker installatie
###

- name: Installeren van Docker op de cluster...
  hosts: pm01
  become: true
  tasks:
    - name: Updaten van packets...
      apt:
        update_cache: yes

    - name: Install Python 3 and pip
      become: yes
      become_user: root
      command: apt install -y python3 python3-pip

    - name: Installeren van Docker...
      apt:
        name: docker.io
        state: present

    - name: Start Docker-service
      service:
        name: docker
        state: started
- name: Installeer pip
  hosts: pm01
  become: true

  tasks:
    - name: Download get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: Voer get-pip.py uit
      command: /usr/bin/python3 /tmp/get-pip.py

    - name: Installeer setuptools
      pip:
        name: setuptools
        state: present

- name: Creëren van de Containers met WordPress...
  hosts: pm01
  gather_facts: yes

  tasks:
    - name: Installeer Docker SDK voor Python
      pip:
        name: docker
        state: present

    - name: Detecteer het pad naar Python
      command: "which python3"
      register: python_path_result

    - set_fact:
        ansible_python_interpreter: "{{ python_path_result.stdout }}"

    - name: WordPress Containers aanmaken
      docker_container:
        name: "wordpress_container_{{ item }}"
        image: wordpress
        memory: 1g
        cpuset_cpus: "1"
        volumes:
          - /home/gebruiker/wordpress:/var/www/html
        ports:
          - "{{ 32767 + item }}:80"
      loop: "{{ range(1, 11) | list }}"

    ###
    ### de wordpress containers zijn aangemaakt
    ###

    - name: Controleer of het aangepaste netwerk bestaat
      docker_network_info:
        name: container_netwerk
      register: network_info

    - name: Creëer een aangepast netwerk
      docker_network:
        name: container_netwerk
        driver: bridge
      when: network_info.exists == False

    - name: Controleer of de containers al aan het netwerk zijn toegevoegd
      docker_network_info:
        name: container_netwerk
        containers: "{{ item }}"
      loop: "{{ range(1, 11) | map('string') | list }}"
      register: network_info_results

    - name: Voeg containers toe aan aangepast netwerk
      command: docker network connect container_netwerk wordpress_container_{{ item.item }}
      loop: "{{ network_info_results.results }}"
      when: not item.changed

      ###controle lijn of alles goed is gegaan
    - name: Controleer of alle containers zijn toegevoegd aan het aangepaste netwerk
      command: docker network inspect container_netwerk
      register: network_inspect


    - name: Beperk de bandbreedte van de containers
      command: >
        tc qdisc add dev eth0 root tbf rate 400mbit burst 8mbit latency 50ms
      args:
        executable: /sbin/tc


    - name: Genereren van SSL-certificaten...
      command: >
        openssl req -x509 -nodes -newkey rsa:4096
        -keyout /etc/ssl/certificaten/key.pem
        -out /etc/ssl/certificaten/cert.pem
      args:
        creates: /etc/ssl/certificaten/

    - name: Voeg gebruikers toe aan de containers
      shell: >
        docker exec -it wordpress_container_{{ item }} /bin/bash -c "
        adduser gebruiker1 &&
        adduser gebruiker2 &&
        openssl req -x509 -nodes -newkey rsa:4096 -keyout /home/gebruiker1/key.pem -out /home/gebruiker1/cert.pem &&
        openssl req -x509 -nodes -newkey rsa:4096 -keyout /home/gebruiker2/key.pem -out /home/gebruiker2/cert.pem
        "
      loop: "{{ range(1, 11) | list }}"

- name: firewall-script uitvoeren voor in de containers
  hosts: pm01
  tasks:
    - name: Kopieer firewall-script naar de containers
      copy:
        src: /home/geenboom1/ansible_wordpress_project/firewall_script.sh
        dest: /tmp/firewall_script.sh

    - name: Voer het firewall-script uit
      command: docker exec -it wordpress_container_{{ item }} /bin/bash -c "/tmp/firewall_script.sh"
      loop: "{{ range(1, 11) | list }}"
