- name: subscriptie uitetten
  hosts:  # Hosts waarop je deze taak wilt uitvoeren
    - pm01
    - pm02
    - pm03
  become: true  # root
  tasks:
    - name: Voeg Proxmox no-subscription repository toe
      blockinfile:
        path: /etc/apt/sources.list
        insertbefore: '## Main'  # toevoegen
        block: |
          # Proxmox VE pve-no-subscription repository provided by proxmox.com,
          # NOT recommended for production use
          deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
          #normalle pakketten van debian
          deb http://deb.debian.org/debian buster main contrib non-free
          deb-src http://deb.debian.org/debian buster main contrib non-free
    - name: pve-enterprise repository weghalen
      lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb'
        line: '# deb'
        state: present

- name: Installeren van Docker op de cluster...
  hosts: pm01
  become: true
  tasks:
    - name: Updaten van packets...
      apt:
        update_cache: yes

    - name: Installeren van python-apt
      apt:
        name: python-apt
        state: present

    - name: Installeren van Docker...
      apt:
        name: docker.io
        state: present

    - name: Start Docker-service
      service:
        name: docker
        state: started

- name: Creëren van de Containers met WordPress...
  hosts: pm01
  tasks:
    - name: 10 WordPress Containers aan het maken...
      command: >
        docker run -d --name wordpress_container_{{ item }}
        --memory=1g --cpus=1
        --volume /home/gebruiker/wordpress:/var/www/html -p {{ 32767 + item }}:80 wordpress
      loop: "{{ range(1, 11) | list }}"


    - name: Creëer een aangepast netwerk
      command: docker network create --driver bridge container_netwerk

    - name: Voeg containers toe aan aangepast netwerk en beperk de bandbreedte
      command: >
        docker network connect container_netwerk wordpress_container_{{ item }} &&
        docker run --rm --net=container_netwerk alpine tc qdisc add dev eth0 root tbf rate 400mbit burst 8mbit latency 50ms
      loop: "{{ range(1, 11) | list }}"


    - name: Genereren van SSL-certificaten...
      command: >
        openssl req -x509 -nodes -newkey rsa:4096
        -keyout /etc/ssl/certificaten/key.pem
        -out /etc/ssl/certificaten/cert.pem
      args:
        creates: /etc/ssl/certificaten/

    - name: Voeg gebruikers toe aan de containers
      shell: >
        docker exec -it wordpress_container_{{ item }} /bin/bash -c "
        adduser gebruiker1 &&
        adduser gebruiker2 &&
        openssl req -x509 -nodes -newkey rsa:4096 -keyout /home/gebruiker1/key.pem -out /home/gebruiker1/cert.pem &&
        openssl req -x509 -nodes -newkey rsa:4096 -keyout /home/gebruiker2/key.pem -out /home/gebruiker2/cert.pem
        "
      loop: "{{ range(1, 11) | list }}"

- name: firewall-script uitvoeren voor in de containers
  hosts: pm01
  tasks:
    - name: Kopieer firewall-script naar de containers
      copy:
        src: /home/geenboom1/ansible_wordpress_project/firewall_script.sh
        dest: /tmp/firewall_script.sh

    - name: Voer het firewall-script uit
      command: docker exec -it wordpress_container_{{ item }} /bin/bash -c "/tmp/firewall_script.sh"
      loop: "{{ range(1, 11) | list }}"
