# Default values for database-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

mysql:
  image:
    repository: mysql
    tag: 5.7
  env:
    MYSQL_ROOT_PASSWORD: yourpassword

adminer:
  image:
    repository: adminer
    tag: latest
  ports:
    - containerPort: 8080

pvc:
  storage: 1Gi