# Weekopdracht_3/HELM/values.yaml
replicaCount: 1

mysql:
  image:
    repository: mysql
    tag: 5.7
  env:
    MYSQL_ROOT_PASSWORD: master

adminer:
  image:
    repository: adminer
    tag: latest
  ports:
    containerPort: 8080

pvc:
  storage: 1Gi