# Weekopdracht_3/HELM/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/managed-by: "Helm"  # Required label
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"  # Required annotation
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"  # Required annotation
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.env.MYSQL_ROOT_PASSWORD }}"