apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          env:
              - name: MYSQL_ROOT_PASSWORD
                value: {{ .Values.mysql.env.MYSQL_ROOT_PASSWORD }}
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: database
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: {{ .Values.adminer.image.repository }}:{{ .Values.adminer.image.tag }}
          ports:
              - containerPort: {{ .Values.adminer.ports.containerPort }}