apache:
  config: apache-config
  namespace: default
  message: "<h1>Hello, World!</h1>"
  name: apache-deployment
  app: apache-app
  replicas: 2
  image: httpd:2.4
  port: 80
  service: apache-service
  protocol: TCP
  targetPort: 80
  ingress:
    enabled: true
    host: example.com
    port: 80
  networkPolicy:
    name: apache-network-policy
    protocol: TCP
    port: 80